pimalaya/himalaya

vim/autoload/himalaya/mbox.vim
Since `fzf` is what is required and not necessarily `fzf.vim` it would be better to just check for this in the `rtp`.
=> Look for fzf instead of fzf.vim

Cargo.lock, Cargo.toml
I believe most of the default clap dependencies are used, this shrinks the dependency tree slightly.
=> Remove unused clap depdenencies

vim/autoload/himalaya/mbox.lua, vim/autoload/himalaya/mbox.vim, vim/autoload/himalaya/msg.vim, vim/autoload/himalaya/shared/cli.vim, vim/autoload/himalaya/shared/log.vim
I started adding preview of mailboxes using telescope. It works well, see (blurred) screencapture below. The only issue is when a mailbox is empty since there is then an error somewhere in the vimscripts I think. @soywod Is there a way to capture this error or perhaps check beforehand if the mailbox is empty or not?
=> Preview mailboxes with telescope

Cargo.lock
This needs to match Cargo.toml to prevent --frozen builds from failing. Can be tested by running `cargo build -j 12 --target x86_64-unknown-linux-gnu --frozen --release` on the master branch where it'll fail and on this branch where it will not.
Should I also update the deployment workflow to use `--frozen` to prevent this in the future? Without an up-to-date lockfile I cannot build this package within NixOS so updating becomes a bit of a hassle :grimacing:
=> Match versions in Cargo lockfile

src/config/model.rs, src/imap/model.rs, src/smtp.rs
This PR allow to use insecure connection for imap and tls via `imap-insecure` and `smtp-insecure` as discussed in #84.
My use case is for testing with [GreenMail](https://greenmail-mail-test.github.io/greenmail/).
=> allow insecure TLS option

README.md, install.sh
Apart from being POSIX compliant this supports configuring install location through standard `PREFIX` environment variable, for example:
```sh
PREFIX="$HOME/.local" sh -c "$(curl -fsSL https://github.com/soywod/himalaya/raw/master/install.sh)"
```
=> Make install script POSIX compliant

README.md, src/config/model.rs, src/msg/model.rs
closes #113 
I started adding an option to change the default '--' to separate the content and signature of a message. While doing so I also merge some common code for the `build_xxx` functions.
=> Added signature separator option plus some refactoring

assets/himalaya.desktop, flake.nix
fixes #160
It seems other projects actually just put this in an `assets/` directory. This would probably be the place say a logo would go. 
The flake could maybe be better overriding the `Exec` with the location in the store, but I think this is good enough and it gives package maintainers a good start.
The `Terminal=true` value makes it be launched in the user's configured terminal
=> Add .desktop file

src/msg/model.rs
Hi! 
I ran into an issue where my emails were being rejected because of a missing Message-Id header.
Since lettre has support for this it was trivial to fix.
Here is a [link](https://github.com/lettre/lettre/blob/0439bab87481dc7ce30c8a79492f14b729df6608/src/message/mod.rs#L357) to lettre's implementation/docs.
~~The default option with None works fine, but it will use the local hostname as the suffix.
Perhaps a better solution would be to use the From header's domain.~~
Message-Id is generated from a uuid and the from address domain.
Happy to make changes as necessary!
=> Add Message-Id header to msg

vim/ftplugin/himalaya-msg-read.vim, vim/ftplugin/himalaya-msg-write.vim
Hello! This PR is more of an opinion thing than a bug fix, but the vim plugin enables the `cursorline` option for the `himalaya-message-list` filetype, as seen below, which makes sense:
However, it also does the same thing for both reading and writing messages, which is something that I believe should be left up to the user, as having cursorline enabled in these buffers is really more of an editor preference thing than it is a UI as in the case of the `himalaya-message-list` filetype. Here are the corresponding screenshots:
If this PR is merged and someone prefers `cursorline` in their read and write buffers, they can easily set that preference themself by placing the following line in their vim/neovim configuration:
```vim
autocmd FileType mail setlocal cursorline
```
=> disable cursorline for read/write in vim plugin

src/output/print.rs
Hi @soywod, this is my second PR because the first one (#248) doesn't allow me to change the source branch from `master` to `development`. In this  PR:
- the target branch is `soywod/development`.
- I use `writeln!` instead of `{}\n`.
- I also tested with zero ZSH configuration. I still see % in the same line, but this PR **will fix** this problem.
Thanks. I'll close #248.
=> add always a newline for the outputs.

email-manager/vim/README.md, email-manager/vim/autoload/himalaya/msg.vim, email-manager/vim/doc/himalaya.txt, email-manager/vim/ftplugin/himalaya-msg-write.vim
This allows users to define a command for contact completion with
`g:himalaya_complete_contact_cmd` and trigger it with `<C-x><C-u>` when
writing an email.
=> Implement contact completion with completefunc

src/msg/msg_entity.rs
When a message is converted to a reply, the `In-Reply-To`-header is set after the message id has already been cleared. This PR reverses the order to fix this issue.
=> Fix replies

vim/plugin/himalaya.vim
This expands the list of supported "full name" commands (i.e.
`Himalaya<Action>`) to match the list of available actions supported by
the default keyboard shortcut bindings for Himalaya. This is mostly
preferential, but it's sometimes easier and faster to invoke vim
commands based on the name of the action you're seeking to perform,
rather than trying to remember a specific keyboard binding.
___
Also, thanks for making Himalaya -- I've really been enjoying using it!
=> vim: match supported commands to available shortcuts

.gitignore, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/config/prelude.rs, src/domain/email/args.rs, src/domain/email/handlers.rs, src/domain/tpl/handlers.rs, src/main.rs, src/ui/editor.rs
* Added `-s|--sanitize` flag for the `read` command.
* Changed the behaviour of the `-t|--mime-type` argument of the `read`
command. It is less strict now: if no part is found for the given
MIME type, it will fallback to the other one. For example, giving
`-t html` will show in priority HTML parts, but if none of them are
found it will show plain parts instead (and vice versa).
* Sanitization is not done by default when using the `read` command,
the flag `-s|--sanitize` needs to be explicitly provided.
* Fixed empty text bodies when reading html part on plain text email
[#352].
* Added pipe support for `(imap|smtp)-passwd-cmd` [#373].
* Added `imap-ssl` and `smtp-ssl` options to be able to disable
encryption [#347].
* Implemented sendmail sender [#351].
* Fixed `process` module for …
=> Release v0.6.1

CHANGELOG.md, CONTRIBUTING.md, Cargo.lock, Cargo.toml, README.md, src/config/config.rs, src/config/prelude.rs, src/config/wizard/maildir.rs, src/config/wizard/mod.rs, src/domain/account/accounts.rs, src/domain/account/config.rs, src/domain/account/handlers.rs, src/domain/folder/args.rs, src/domain/folder/handlers.rs, src/main.rs
- Added command `folders expunge` that deletes all emails marked for
deletion.
- Changed the location of the
[documentation](https://pimalaya.org/himalaya/docs/).
- Fixed broken links in README.md.
- Removed the `maildir-backend` cargo feature, it is now included by
default.
- Removed issues section on GitHub, now issues need to be opened by
sending an email at
[~soywod/pimalaya@todo.sr.ht](mailto:~soywod/pimalaya@todo.sr.ht).
- Added ability to synchronize specific folders only [#37].
- Added `Backend::expunge` function that definitely removes emails
with the `Deleted` flag.
- Added `Backend::mark_emails_as_deleted` function with a default
implementation that adds the `Deleted` flag.
- Changed the way emails are deleted. `Backend::delete_emails` now
moves the email to the `Trash` folder …
=> Release v0.7.1

README.md
`himalaya` packaged for Fedora/CentOS/RHEL and available in [COPR](https://copr.fedorainfracloud.org/coprs/atim/himalaya/).
=> docs: Add Fedora/CentOS installation instructions

src/lib.rs
i'm working on updating the nixos module definitions for himalaya to be able to build the most recent 1.0.0-beta. when building with the next version of rust about to be available in nixpkgs (1.70.0), this ambiguous export was found and preventing building. the version of rust used in this repo's nix environment allows the build to proceed. locally, i updated the `flake.nix` to more closely emulate the build environment of nixpkgs. i can commit that as well in this PR if desired.
=> fix ambiguous email export

src/account/mod.rs
when default features are turned off and the `sendmail` feature isn't enabled, it doesn't build. this fixes that.
=> allow account.sendmail when sendmail feature is on

README.md, default.nix
This way you can do
```nix
himalaya.override {
buildFeatures = [ "notmuch" "oauth2" ];
}
```
Also this uses any unspecified arguments as if they were given from `pkgs`, so no need to explicitly specify.
See also pimalaya/mirador#5 pimalaya/neverest#15
=> Allow using `override` to add features

CONTRIBUTING.md
Standardizing commit style is welcome, but I was not aware of what Conventional Commits are, and their repository does not describe what the commits are meant to look like. Linking to the summary is IMHO more convenient.
Uh, for clarity: I was just curious about what Conventional Commits are, I am far from being familiar enough with the code base to contribute anything substantial other than hopefully helpful bug reports.
=> docs: link to conventionalcommits.org instead of their repo

README.md
When attempting to use the gmail provider example I was getting errors pointing to the line `backend.type.host`. I compared the configuration to the other examples and found none of them had the additional `type` in their other settings. This worked for me so I'm guessing it's just a typo.
=> Fix gmail doc example
