pimalaya/himalaya

- vim/autoload/himalaya/mbox.vim
otherwise gives:
```
Vim(else):E488: Trailing characters:     else if &rtp =~
```
> else if -> elseif

- src/smtp.rs
> Respect smtp port when sending email

- src/smtp.rs
change for #103 after @paolobarbolini explanation and help !
> allow insecure TLS option, second try

- README.md
- install.sh
Read the commit messages for commentary. See also #53 and #66.
> Improve portability of install.sh

- src/config/model.rs
- Fix https://github.com/soywod/himalaya/issues/72#issuecomment-822101907
- Use `USERPROFILE` as alternative HOME on Windows
> fix: fix config loading compatibility on Windows

- src/main.rs
> handle completions subcommand first

- src/msg/model.rs
> add content-transfer-encoding support

- Cargo.lock
- Cargo.toml
- src/msg/model.rs
[Updates lettre to v0.10.0-rc.1](https://github.com/lettre/lettre/releases/tag/v0.10.0-rc.1)
> Update lettre to v0.10.0-rc.1

- src/msg/cli.rs
Hi.
I found that your codebase is not very DRY. This is a first step, **it is a draft because I can do a lot more I guess**.
Would you like me to go on, or are these kind of changes not wanted?
---
Also: If these changes are wanted, I don't know how much progress there is in this repository. If there is a lot, I will chunk up my refactoring PRs so that we do not run into too many merge conflicts!
> Refactor msg matches

- flake.lock
- flake.nix
outdated comment from putting the plugin inside the main derivation
> himalaya-vim nix package

- flake.lock
- flake.nix
The Vim plugin was failing to build. I opened an upstream [merge request](https://github.com/NixOS/nixpkgs/pull/132517) in `nixpkgs` as well.
> Fix Vim plugin + update Flake references

- email-manager/src/config/account_entity.rs
- email-manager/src/domain/imap/imap_handler.rs
- email-manager/src/domain/imap/imap_service.rs
- email-manager/src/domain/mbox/mboxes_entity.rs
- email-manager/src/domain/msg/envelope_entity.rs
- email-manager/src/domain/msg/envelopes_entity.rs
- email-manager/src/domain/msg/flags_entity.rs
- email-manager/src/domain/msg/msg_arg.rs
- email-manager/src/domain/msg/msg_entity.rs
- email-manager/src/domain/msg/msg_handler.rs
- email-manager/src/domain/msg/parts_entity.rs
- email-manager/src/main.rs
- email-manager/src/output/output_entity.rs
- email-manager/src/ui/table.rs
This commit should have no impact on the behavior of the program.
I couldn't find any documentation on what the testing procedure is. Both `cargo test` and `cargo test --release` are happy.
Feel free to point me towards more in-depth tests.
> clean: fix clippy lints

- .gitignore
- flake.lock
- flake.nix
> Nix run issue

- CHANGELOG.md
- src/domain/msg/msg_arg.rs
- src/domain/msg/msg_handler.rs
- src/domain/msg/tpl_arg.rs
- src/domain/msg/tpl_handler.rs
- src/main.rs
- vim/autoload/himalaya/msg.vim
- vim/ftplugin/himalaya-msg-write.vim
> Add attachments with save and send commands

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LICENSE
- src/domain/imap/imap_service.rs
- src/domain/msg/msg_arg.rs
- src/domain/msg/msg_handler.rs
- src/domain/msg/tpl_arg.rs
- src/domain/msg/tpl_handler.rs
- src/main.rs
- vim/README.md
- vim/autoload/himalaya/msg.vim
- vim/ftplugin/himalaya-msg-write.vim
- Add attachments with save and send commands [#47] [#259]
- Invalid sequence set [#276]
> Release v0.5.4

- src/config/account_entity.rs
- src/config/config_entity.rs
- src/domain/imap/imap_handler.rs
- src/domain/imap/imap_service.rs
- src/domain/mbox/mbox_handler.rs
- src/domain/msg/flag_handler.rs
- src/domain/msg/msg_entity.rs
- src/domain/msg/msg_handler.rs
- src/domain/msg/tpl_handler.rs
- src/domain/smtp/smtp_service.rs
- src/main.rs
Most of the changes are in `account_entity` and `config_entity`, the rest is just renaming `imap` into `backend`.
> Introduce backends

- rustfmt.toml
- src/config/account_config.rs
- src/config/deserialized_account_config.rs
This should fix https://github.com/soywod/himalaya/issues/305.
Please note that I'm pretty overwhelmed by the new code so I was pretty unsure how to test it.
I'd be happy if some of you guys could quickly try this branch out and give a submission :)
> 305 maildir expansion

- vim/autoload/himalaya/msg.vim
my msg_id's look like: b85, d39, ae0, etc.
and I get this error when using the vim plugin:
Error: cannot find maildir message by short hash "0" at "/path/to/my/INBOX"
Caused by:
0: cannot find maildir message id from short hash "0"
1: the short hash "0" matches more than one hash: 030598120934103c456ce08338886728, 06edb10a55efb89de45d8560aee33c8e
Signed-off-by: Robert Günzler <r@gnzler.io>
> vim: msg_id is a string

- Cargo.lock
- lib/Cargo.toml
TL;DR:
- Just adjusted the version of lettre :D
should fix https://github.com/soywod/himalaya/issues/292
> 292 cannot build sendable message missing destination address invalid envelope

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/config/config.rs
- src/domain/account/config.rs
- src/domain/account/handlers.rs
- src/domain/email/args.rs
- src/domain/email/handlers.rs
- src/domain/flag/args.rs
- src/domain/flag/handlers.rs
- src/domain/folder/handlers.rs
- src/domain/imap/handlers.rs
- src/domain/tpl/args.rs
- src/domain/tpl/handlers.rs
- src/main.rs
- src/printer/print.rs
- src/printer/printer.rs
- src/ui/editor.rs
The composer has been written in a dedicated repository https://git.sr.ht/~soywod/mime-msg-builder.
> Integrate the email composer mime-msg-builder

- README.md
Hi, `himalaya` has been added to Scoop package manager (see https://repology.org/project/himalaya/versions). 
Could you please update the https://pimalaya.org/himalaya/docs/cli/installation.html page as well? Thanks!
> Add Scoop install method

- config.sample.toml
I had to update my personal config after the recent update so I thought I'd update the sample config here as well. But I don't actually use Gmail with Himalaya so hasn't tested this particular config.
> update sample config to v0.8

- Cargo.toml
- src/cli.rs
- **Trying to enable clap integration with environment variables.**
- **Using HIMALAYA_CONFIG as a way to provide himalaya configuration file from environment.**
> Enabling HIMALAYA_CONFIG to locate configuration file.

- flake.lock
- flake.nix
Fixes #483
I thought I'd have a try at doing this, also made the package more normal package like, and doing the artifact building in the CI (though to keep the zip/tar paths same the command is not super great).
I also want to have a look at adding feature flags, though can't get `withNotmuch` to build yet, it can't find `-lnotmuch`, it doesn't seem to end up in the libs for some reason, though it does start out in `NIX_LDFLAGS`.
> Draft: Use crane instead of naersk
